### ISSUE TITLE
Evaluation issue:

### ISSUE THREAD

**Issue by Mei0211** [Vchitect/VBench#4]
I wrote a script for evaluation,but I encoutered a issue then:
1、script:
from vbench import VBench
import torch
device = torch.device("cuda")
my_VBench = VBench(device, "VBench_full_info.json", "evaluation_results")
my_VBench.evaluate(
    videos_path = "./videocrafter/spatial_relationship", #there are several videos  in this directory
    name = "spatial_relationship",
    dimension_list = ["spatial_relationship"],
    )
2、issue:
RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

3、evaluate results:
![image](https://github.com/Vchitect/VBench/assets/61417471/2e0e0b2b-5945-4b88-bdaf-094594e19b99)

**Comment by JustinYuu** [comment]
Hi, thanks for your interest in our work!
The issue may be attributed to the wrong sampled video format. As we mentioned in the [How to Sample Videos for Evaluation](https://github.com/Vchitect/VBench/tree/master/prompts) section, the names of videos should be in the form of **$prompt-$index.mp4**. You can refer to the **$dimension_full_info.json** in the _evaluation_reuslts/_ folder to check if the sampled videos exist in the _“video_list"_ key of each prompt.

**Comment by mei1127** [comment]
Thanks for your information！I‘ll try it later！

**Comment by ziqihuangg** [comment]
Hi, we're closing this issue as it appears your questions have been addressed. However, feel free to open a new issue or reopen this one, if you have further questions or if anything else comes up related to this issue.

**Comment by rahimentezari** [comment]
still getting NaN with generated input from [Mochi g-drive](https://drive.google.com/file/d/1zDlDQmtR3SGZzWmNCoeFe0jKACxloWqR/view), for example:
An astronaut feeding ducks on a sunny afternoon, reflection from the water.-4.mp4
